version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.2.0
commands:
  install_flutter:
    description:
      Install Flutter and set up paths.
    parameters:
      flutter_version:
        description: Flutter version
        type: string
        default: stable
    steps:
      - run:
          name: Set up Flutter
          command: |
            echo 'export FLUTTER_HOME=${HOME}/sdks/flutter' >> $BASH_ENV
            echo 'export FLUTTER_VERSION=<< parameters.flutter_version >>' >> $BASH_ENV
            echo 'export FLUTTER_ROOT=${FLUTTER_HOME}' >> $BASH_ENV
            echo 'export PATH=${PATH}:${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin:${HOME}/.pub-cache/bin' >> $BASH_ENV
            source $BASH_ENV
            git clone --branch ${FLUTTER_VERSION} https://github.com/flutter/flutter.git ${FLUTTER_HOME}
            (yes || true) | flutter doctor --android-licenses && flutter doctor
  pre_start_ios_simulator:
    description: >-
      Pre start simulator, build may fail if simulator is not started.
    steps:
      - run:
          name: Pre-start simulator
          command: ./.circleci/pre_start_ios_simulator.sh
  macos_setup_android:
    description: >-
      Set up the Android environment in macOS.
    steps:
      - run:
          name: Set up env
          command: ./.circleci/android-flutter.sh export-env
      - run:
          name: Install Android SDK from Homebrew
          command: |
            brew tap homebrew/cask >/dev/null
            brew cask install android-sdk >/dev/null
      - run:
          name: Install emulator from SDK manager
          command: ./.circleci/android-flutter.sh sdkmanager
  setup_android_emulator:
    description: >-
      Setup Android emulator.
    steps:
      - run:
          name: Setup emulator
          command: |
            echo "no" | avdmanager create avd --force --name TestingAVD -k "system-images;android-28;default;x86_64" --tag default --device pixel
      - run:
          name: Launch emulator
          command: |
            export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
            emulator -avd TestingAVD -cores 1 -gpu auto -accel on -memory 1024 -no-audio -no-snapshot -no-boot-anim -no-window
          background: true
      - run:
          name: Launch logcat
          command:
            adb logcat > logcat.log
          background: true
      - run:
          name: Wait emulator
          command: |
            ./.circleci/android-flutter.sh wait-for-avd
            python3 .circleci/unlock_emulator_screen.py
jobs:
  build:
    docker:
      - image: circleci/android:api-29
    resource_class: large
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - install_flutter
      - checkout
      - run: flutter build
  unit_test:
    docker:
      - image: circleci/android:api-29
    resource_class: large
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - install_flutter
      - checkout
      - run: flutter test
  int_test_emulator_android:
    macos:
      xcode: "11.4.1"
    environment:
      JVM_OPTS: -Xmx3200m
      HOMEBREW_NO_AUTO_UPDATE: '1'
    steps:
      - checkout
      - macos_setup_android
      - install_flutter
      - setup_android_emulator
      - run:
          name: Run flutter drive
          no_output_timeout: 30m
          command: flutter drive --target=test_driver/app.dart
      - store_artifacts:
          path: logcat.log
  int_test_emulator_ios:
    macos:
      xcode: "11.4.1"
    steps:
      - checkout
      - install_flutter
      - pre_start_ios_simulator
      - run:
          name: Run flutter drive
          no_output_timeout: 30m
          command: flutter drive --target=test_driver/app.dart
      - store_artifacts:
          path: logcat.log
  int_test_device_farm:
    docker:
      - image: circleci/android:api-29
    resource_class: large
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - install_flutter
      - run:
          name: Install sylph from pub
          command: pub global activate sylph
      - checkout
      - aws-cli/setup
      - run:
          name: Run sylph
          command: $HOME/.pub-cache/bin/sylph
workflows:
  run_tests:
    jobs:
      - unit_test
      - int_test_emulator_android
      - int_test_emulator_ios
      - int_test_device_farm
